### ISSUE TITLE
TODO: SET IMAGE FOR OpenGraph and Twitter

### ISSUE THREAD

**Issue by K-Sato1995** [K-Sato1995/blog#1]

**Comment by kwaicsse** [comment]
@K-Sato1995，同学，您好，这个项目您还在维护吗？上面的漏洞报告是我IDE运行时，安全插件提示您这个项目存在的几个漏洞的报告，辛苦您修复一下哈，担心其他人也会用到你这个项目，从而引入这些漏洞。：）
